

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
/**
 *
 * @author DELL
 */
public class Chatwindow extends javax.swing.JFrame {
    private Socket soc = null;
    public File selectedfile;
    /**
     * Creates new form Chatwindow
     */
    public Chatwindow() {
        initComponents(); 
    }
    
    public Socket getSocket() {
        return soc;
    }
            
    
    void Connect()
    {
        System.out.println("Connecting To server...");
                try {
                    soc = new Socket("localhost",8818);
                    System.out.println("Connected with server"+soc);
                } catch (IOException ex) {
                    Logger.getLogger(Chatwindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                MessageReciever m1 = new MessageReciever(this);
                Thread t1 = new Thread(m1);
                t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nameofuser = new javax.swing.JLabel();
        Recievername = new javax.swing.JLabel();
        Messagefield = new javax.swing.JTextField();
        Sendbutton = new javax.swing.JButton();
        Fileattachbutton = new javax.swing.JButton();
        Filenamedisplay = new javax.swing.JTextField();
        Sendfilebutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messagedisplaybox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Nameofuser.setText("User");

        Recievername.setText("Grp Name");

        Sendbutton.setText("Send");
        Sendbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendbuttonActionPerformed(evt);
            }
        });

        Fileattachbutton.setText("Attach A file");
        Fileattachbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileattachbuttonActionPerformed(evt);
            }
        });

        Filenamedisplay.setEditable(false);
        Filenamedisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilenamedisplayActionPerformed(evt);
            }
        });

        Sendfilebutton.setText("Send File");
        Sendfilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendfilebuttonActionPerformed(evt);
            }
        });

        messagedisplaybox.setColumns(20);
        messagedisplaybox.setRows(5);
        jScrollPane2.setViewportView(messagedisplaybox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nameofuser, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Recievername))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Messagefield, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sendbutton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Filenamedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fileattachbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sendfilebutton)
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nameofuser, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(Recievername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Messagefield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sendbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Filenamedisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sendfilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Fileattachbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int SendMessage()
{
    try {
            String message  = Messagefield.getText()+"~Vivek:";
            PrintWriter out =new PrintWriter(soc.getOutputStream(),true);
            out.println(message);
            System.out.println("Message sent to server");
        } catch (IOException ex) 
        {
            ex.printStackTrace();
        }  
    return 0;
}
//int RecieveMessage()
//{
//        BufferedReader in;
//        try {
//            in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
//        } catch (IOException ex) {
//            return 0;
//        }
//        try {
//            messagedisplaybox.append(in.readLine());
//        } catch (IOException ex) {
//            return 0;
//        }
//                    messagedisplaybox.append("\n");
//        return 1;
//}
    private void SendbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendbuttonActionPerformed

        SendMessage();
    }//GEN-LAST:event_SendbuttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
    }//GEN-LAST:event_formWindowOpened

    private void FileattachbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileattachbuttonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        selectedfile = fc.getSelectedFile();
        String filename = selectedfile.getName();
        Filenamedisplay.setText(filename);
    }//GEN-LAST:event_FileattachbuttonActionPerformed

    private void FilenamedisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilenamedisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilenamedisplayActionPerformed

    private void SendfilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendfilebuttonActionPerformed
        FileInputStream fin=null;
        try {
            String filepath=selectedfile.getAbsolutePath();
            fin = new FileInputStream(filepath);  
            byte b[]=new byte[9999999];
            fin.read(b,0,b.length);
            OutputStream os=soc.getOutputStream();
            os.write("!!FILEINCOMING!!".getBytes());
            os.flush();
            os = soc.getOutputStream();
            os.write(b, 0, b.length);
            System.out.println("File Send");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Chatwindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Chatwindow.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fin.close();
            } catch (IOException ex) {
                Logger.getLogger(Chatwindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SendfilebuttonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fileattachbutton;
    public javax.swing.JTextField Filenamedisplay;
    private javax.swing.JTextField Messagefield;
    protected javax.swing.JLabel Nameofuser;
    protected javax.swing.JLabel Recievername;
    private javax.swing.JButton Sendbutton;
    private javax.swing.JButton Sendfilebutton;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea messagedisplaybox;
    // End of variables declaration//GEN-END:variables
}
